name = "Aaaa Modpack"
author = "Kneelawk"
version = "2.14.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "263d4f57e013d7435ba2793544f5624dcece619111026dbb496d93e8a4f4629a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
