name = "Aaaa Modpack"
author = "Kneelawk"
version = "2.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8b155d63d899e1e3adb1ed1f21d787fc8658d1596291a987f8197fc100a30a3"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
