name = "Aaaa Modpack"
author = "Kneelawk"
version = "2.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d02eff475ec30f2bc537a2a27d0cd283e19ba332ada8ee2b16566bd1d500fd0"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
