name = "Aaaa Modpack"
author = "Kneelawk"
version = "2.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e48b91adcf5184b45f19e2f2dfc3d75e7ee2da38dd25ef54728b75a470aa412"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
