name = "Aaaa Modpack"
author = "Kneelawk"
version = "1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab5be05bebcd84487301d903daa51bbe03d06aad97222add47a72843dc355cee"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
