name = "Aaaa Modpack"
author = "Kneelawk"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "599334b1ba9530123a6ccc0c39a08d66e413bb5bb0d7fe384312c4078b42b790"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
