name = "Aaaa Modpack"
author = "Kneelawk"
version = "2.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6acddb638cca75467f26b5f75d45f0dfd70a29f04e8726198cb01a59449a4ea1"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
